### ISSUE TITLE
Unrecognized cop Rspec when inherit together with action policy

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [SwitchDreams/switchcop#1]
With this rubocop config
```yaml
# rubocop.yml
inherit_gem:
  switchcop: rubocop.yml
  action_policy: config/rubocop-rspec.yml
```

When I run `rubocop`, it shows this error:

`Error: unrecognized cop or department RSpec found in /home/pedro/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/action_policy-0.6.3/config/rubocop-rspec.yml
`

For workaround, adds this line in the start of rubocop.yml:

```
require:
  - rubocop-rspec
```
